### ISSUE TITLE
Send update to participants

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#62]
On March 13, @trberg said that the Validation UW dataset is still no ready. I would like to send an email communication to participants to give them an update on Validation timeline + collaborative phase (#61 ).

## Tasks

- [x] Get timeline information from #61 
- [x] Get latest update from @trberg during today's meeting
- [x] Draft email communication
- [x] Send email communication

**Comment by tschaffter** [comment]
Email communication has been sent a month ago.
